# =====================================================
# BarberSmart - Docker Swarm Stack
# =====================================================
# Deploy via Portainer ou CLI:
# docker stack deploy -c docker-stack.yml barbersmart
# =====================================================

version: "3.8"

services:
  # =====================================================
  # BarberSmart Application
  # =====================================================
  app:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-barbersmart/app}:${IMAGE_TAG:-latest}
    networks:
      - web
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        # Traefik Configuration
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        
        # Main Domain Router
        - "traefik.http.routers.barbersmart-main.rule=Host(`${MAIN_DOMAIN:-barbersmart.app}`) || Host(`www.${MAIN_DOMAIN:-barbersmart.app}`)"
        - "traefik.http.routers.barbersmart-main.entrypoints=websecure"
        - "traefik.http.routers.barbersmart-main.tls.certresolver=letsencrypt"
        - "traefik.http.routers.barbersmart-main.priority=10"
        
        # Wildcard Subdomain Router
        - "traefik.http.routers.barbersmart-wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${MAIN_DOMAIN:-barbersmart.app}`)"
        - "traefik.http.routers.barbersmart-wildcard.entrypoints=websecure"
        - "traefik.http.routers.barbersmart-wildcard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.barbersmart-wildcard.priority=5"
        
        # Service Configuration
        - "traefik.http.services.barbersmart.loadbalancer.server.port=80"
        - "traefik.http.services.barbersmart.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.barbersmart.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.barbersmart.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.barbersmart.loadbalancer.sticky.cookie.name=barbersmart_sticky"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # =====================================================
  # Traefik Reverse Proxy (opcional se já existe)
  # =====================================================
  traefik:
    image: traefik:v3.0
    command:
      # API and Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      
      # Docker Swarm Provider
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=web"
      
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      
      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@barbersmart.app}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      
      # Logging
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - web
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # Dashboard (opcional - proteger com auth em produção)
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${MAIN_DOMAIN:-barbersmart.app}`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"

networks:
  web:
    external: true
    driver: overlay
    attachable: true

volumes:
  traefik-certs:
    driver: local
